import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtemp,mkdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import net from 'node:net';
import {chromium} from 'playwright';
import {openDatabase} from '../src/db.js';
test('人工复核界面保存原文引用、保留草稿冲突并查看独立统计',{skip:!process.env.GEO_UI_TEST},async()=>{
 const dir=await mkdtemp(join(tmpdir(),'geo-review-ui-')),dbPath=join(dir,'test.db'),db=openDatabase(dbPath),now='2026-10-08T00:00:00Z';
 db.prepare('INSERT INTO brands(id,name,created_at,updated_at) VALUES(1,?,?,?)').run('星河工具',now,now);
 db.prepare("INSERT INTO questions(id,brand_id,text,kind,source,created_at) VALUES(1,1,'有哪些工具？','discovery','manual',?)").run(now);
 db.prepare("INSERT INTO tasks(id,brand_id,name,platforms_json,question_ids_json,account_ids_json,schedule_type,created_at) VALUES(1,1,'人工复核示例','[\"doubao\"]','[1]','[1]','manual',?)").run(now);
 db.prepare("INSERT INTO runs(id,task_id,status,total,done,started_at,finished_at) VALUES(1,1,'completed',1,1,?,?)").run(now,now);
 const answer='星河工具\r\n😀 <img src=x onerror=window.reviewBad=true>重复词；重复词';
 db.prepare("INSERT INTO results(id,run_id,question_id,platform,account_id,status,answer,started_at,finished_at) VALUES(1,1,1,'doubao',1,'succeeded',?,?,?)").run(answer,now,now);
 db.prepare("INSERT INTO runs(id,task_id,status,total,done,started_at,finished_at) VALUES(2,1,'completed',0,0,?,?)").run(now,now);db.close();
 const listener=net.createServer();await new Promise(done=>listener.listen(0,'127.0.0.1',done));const port=listener.address().port;await new Promise(done=>listener.close(done));
 const child=spawn(process.execPath,['src/server.js'],{cwd:resolve('.'),env:{...process.env,GEO_PORT:String(port),GEO_DB_PATH:dbPath,GEO_RESULTS_ROOT:join(dir,'results'),GEO_PROFILE_ROOT:join(dir,'profiles')},stdio:['ignore','pipe','pipe']});let browser,errors='';child.stderr.on('data',c=>errors+=c);
 try{
  let ready=false;for(let i=0;i<60;i++){if(child.exitCode!==null)throw Error(errors);try{await fetch('http://127.0.0.1:'+port+'/api/bootstrap');ready=true;break;}catch{}await new Promise(done=>setTimeout(done,100));}assert.ok(ready);
  browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1440,height:950}});await page.goto('http://127.0.0.1:'+port);
  await page.locator('[name=username]').fill('admin');await page.locator('[name=password]').fill('sample-password-123');await page.getByRole('button',{name:'创建管理员',exact:true}).click();
  await page.getByRole('button',{name:'采集结果',exact:true}).click();await page.locator('[data-action="viewRun"][data-id="1"]').click();
  await page.locator('summary').filter({hasText:'有哪些工具？'}).click();await page.getByRole('button',{name:'人工复核',exact:true}).click();await page.locator('#answerReviewOriginal').waitFor();
  assert.equal(await page.locator('#answerReviewOriginal').textContent(),answer);assert.equal(await page.locator('#answerReviewOriginal img').count(),0);
  await page.locator('#answerReviewForm [name=status]').selectOption('inaccurate');await page.locator('#answerReviewForm [name=notes]').fill('\n<img src=x onerror=window.reviewBad=true>资料需要核对');
  await page.getByRole('button',{name:'刷新',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('[data-action="refresh"]').disabled);assert.equal(await page.locator('#answerReviewForm [name=notes]').inputValue(),'\n<img src=x onerror=window.reviewBad=true>资料需要核对');
  await page.route('**/api/runs',async route=>{const response=await route.fetch(),data=await response.json();data.runs.find(r=>r.id===2).status='running';await route.fulfill({response,json:data});});
  await page.locator('[data-action="viewRun"][data-id="2"]').click();await page.waitForFunction(()=>!document.querySelector('[data-action="refresh"]').disabled);
  let otherRunRefreshes=0;const track=request=>{if(request.url().endsWith('/api/runs/2'))otherRunRefreshes++;};page.on('request',track);
  await page.waitForFunction(()=>!document.querySelector('[data-action="refresh"]').disabled);await new Promise(done=>setTimeout(done,5600));page.off('request',track);await page.unroute('**/api/runs');
  assert.ok(otherRunRefreshes>0,'隐藏草稿不能暂停其他运行刷新');
  await page.waitForFunction(()=>!document.querySelector('[data-action="refresh"]').disabled);await page.locator('[data-action="viewRun"][data-id="1"]').click();await page.locator('#answerReviewForm').waitFor();await page.waitForFunction(()=>!document.querySelector('[data-action="refresh"]').disabled);
  assert.equal(await page.locator('#answerReviewForm [name=notes]').inputValue(),'\n<img src=x onerror=window.reviewBad=true>资料需要核对');
  await page.locator('#answerReviewOriginal').evaluate(pre=>{const text=pre.firstChild,start=text.textContent.lastIndexOf('重复词'),range=document.createRange();range.setStart(text,start);range.setEnd(text,start+3);const selection=window.getSelection();selection.removeAllRanges();selection.addRange(range);});
  assert.equal(await page.evaluate(()=>window.getSelection().toString()),'重复词');await page.getByRole('button',{name:'引用选中的原文',exact:true}).click();await page.locator('#answerReviewForm blockquote').waitFor({timeout:3000}).catch(async error=>{throw Error(error.message+' UI '+await page.locator('main').innerText());});assert.equal(await page.locator('#answerReviewForm blockquote').innerText(),'重复词');
  await mkdir(resolve('work'),{recursive:true});await page.screenshot({path:resolve('work','geo-answer-review-editor.png'),fullPage:true});
  await page.getByRole('button',{name:'保存复核',exact:true}).click();await page.getByText('人工复核已保存，提及统计保持原口径。',{exact:true}).waitFor();
  let saved=await (await page.request.get('http://127.0.0.1:'+port+'/api/results/1/review')).json();assert.equal(saved.review.excerpt.start,answer.lastIndexOf('重复词'));assert.equal(saved.review.status,'inaccurate');assert.equal(await page.evaluate(()=>window.reviewBad),undefined);assert.equal(await page.locator('.answer-review img').count(),0);
  await page.getByRole('button',{name:'人工复核',exact:true}).click();await page.locator('#answerReviewForm [name=status]').selectOption('uncertain');await page.locator('#answerReviewForm [name=notes]').fill('保存成功但刷新断网');
  await page.route('**/api/brands',route=>route.abort());await page.getByRole('button',{name:'保存复核',exact:true}).click();await page.getByText('复核已保存，但页面刷新失败，请稍后刷新：Failed to fetch',{exact:true}).waitFor();assert.equal(await page.locator('#answerReviewForm').count(),0);
  saved=await (await page.request.get('http://127.0.0.1:'+port+'/api/results/1/review')).json();assert.equal(saved.review.status,'uncertain');
  await page.unroute('**/api/brands');await page.getByRole('button',{name:'刷新',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('[data-action="refresh"]').disabled);await page.locator('details[data-result-id="1"] > summary').click();
  await page.getByRole('button',{name:'人工复核',exact:true}).click();await page.locator('#answerReviewForm [name=notes]').fill('我的未保存草稿');
  await page.request.put('http://127.0.0.1:'+port+'/api/results/1/review',{data:{status:'outdated',notes:'另一次保存',excerpt:null,expectedRevision:saved.review.revision,expectedUpdatedAt:saved.review.updatedAt}});
  await page.getByRole('button',{name:'保存复核',exact:true}).click();await page.getByText('回答或复核已变化，请重新打开复核；当前草稿可保留复制',{exact:true}).waitFor();assert.equal(await page.locator('#answerReviewForm [name=notes]').inputValue(),'我的未保存草稿');
  await page.getByRole('button',{name:'关闭复核',exact:true}).click();await page.getByRole('button',{name:'分析报告',exact:true}).click();await page.getByRole('heading',{name:'人工复核 · 团队标记',exact:true}).waitFor();
  await page.locator('.manual-review-summary [data-id="review|outdated"]').click();assert.match(await page.locator('#reportEvidence').innerText(),/统计对应的回答 · 1 条/);assert.match(await page.locator('#reportEvidence').innerText(),/信息过时/);
  await page.getByRole('button',{name:'关闭证据',exact:true}).click();await mkdir(resolve('work'),{recursive:true});await page.screenshot({path:resolve('work','geo-answer-review.png'),fullPage:true});
 }finally{await browser?.close();if(child.exitCode===null){child.kill();await new Promise(done=>child.once('exit',done));}}
});
