import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdtemp, mkdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import net from 'node:net';
import { chromium } from 'playwright';
import { openDatabase } from '../src/db.js';
import { PLATFORMS } from '../src/browser.js';

test('本地界面可完成品牌、问题和任务创建', { skip: !process.env.GEO_UI_TEST }, async () => {
  const dir = await mkdtemp(join(tmpdir(), 'geo-ui-test-'));
  await mkdir(resolve('work'), { recursive: true });
  const listener = net.createServer();
  await new Promise(done => listener.listen(0, '127.0.0.1', done));
  const port = listener.address().port;
  await new Promise(done => listener.close(done));
  const child = spawn(process.execPath, ['src/server.js'], {
    cwd: resolve('.'),
    env: { ...process.env, GEO_PORT: String(port), GEO_DB_PATH: join(dir, 'test.db'),
      GEO_BROWSER_CHANNEL: 'intentionally-unavailable-test-browser', GEO_PROFILE_ROOT: join(dir, 'profiles'), GEO_RESULTS_ROOT: join(dir, 'results') },
    stdio: ['ignore', 'pipe', 'pipe'],
  });
  let browser;
  try {
    for (let i = 0; i < 50; i++) {
      try { await fetch('http://127.0.0.1:' + port + '/api/bootstrap'); break; } catch {}
      await new Promise(done => setTimeout(done, 100));
    }
    browser = await chromium.launch({ channel: 'msedge', headless: true });
    const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
    await page.goto('http://127.0.0.1:' + port);
    await page.locator('input[name="username"]').fill('admin');
    await page.locator('input[name="password"]').fill('sample-password-123');
    await page.getByRole('button', { name: '创建管理员' }).click();
    await page.getByRole('button', { name: '退出登录' }).click();
    await page.locator('input[name="username"]').fill('admin');
    await page.locator('input[name="password"]').fill('incorrect-password');
    await page.getByRole('button', { name: '登录', exact: true }).click();
    await page.getByText('用户名或密码错误', { exact: true }).waitFor();
    assert.equal(await page.locator('input[name="username"]').inputValue(), 'admin');
    await page.locator('input[name="password"]').fill('sample-password-123');
    await page.getByRole('button', { name: '登录', exact: true }).click();
    await page.getByRole('button', { name: '品牌资料' }).click();
    await page.locator('input[name="name"]').fill('星河');
    await page.locator('input[name="category"]').fill('数据分析工具');
    await page.getByRole('button', { name: '保存品牌资料' }).click();
    await page.getByRole('button', { name: '新建品牌', exact: true }).click();
    await page.getByRole('button', { name: '问题池' }).click();
    const manualQuestion = '有哪些适合小企业的数据分析工具？';
    await page.locator('#manualQuestionsForm textarea').fill(manualQuestion);
    const saveRequest = page.waitForResponse(response => response.request().method() === 'POST' && response.url().endsWith('/questions'));
    await page.getByRole('button', { name: '加入问题池', exact: true }).click();
    const saved = await saveRequest;
    assert.equal(saved.status(), 201, '离开未保存的新品牌页面后，应使用下拉框显示的有效品牌保存问题');
    await page.getByText(manualQuestion, { exact: true }).waitFor({ timeout: 5000 });
    await page.locator('#manualQuestionsForm textarea').fill('x'.repeat(501));
    await page.getByRole('button', { name: '加入问题池', exact: true }).click();
    await page.getByText('问题过长', { exact: true }).waitFor();
    assert.equal((await page.locator('#manualQuestionsForm textarea').inputValue()).length, 501);
    await page.getByRole('button', { name: '根据品牌资料出题' }).click();
    await page.getByRole('button', { name: '审核后加入问题池' }).click();
    await page.getByText(/已加入 \d+ 个新问题/).waitFor({ timeout: 5000 });
    await page.locator('#topicForm input[name="name"]').fill('选择比较');
    await page.locator('#topicForm button').first().click();
    await page.getByText('选择比较 · 0 个问题',{exact:true}).waitFor();
    await page.locator('#topicMembershipForm [name="question"]').first().check();
    await page.locator('#topicMembershipForm [name="topicId"]').selectOption({label:'选择比较（0）'});
    await page.locator('#topicMembershipForm button').click();
    await page.getByText('选择比较 · 1 个问题',{exact:true}).waitFor();
    await page.locator('#topicForm input[name="name"]').fill('场景问题');
    await page.locator('#topicForm button').first().click();
    await page.getByText('场景问题 · 0 个问题',{exact:true}).waitFor();
    await page.locator('#topicMembershipForm [name="question"]').first().check();
    await page.locator('#topicMembershipForm [name="topicId"]').selectOption({label:'场景问题（0）'});
    await page.locator('#topicMembershipForm button').click();
    await page.getByText('场景问题 · 1 个问题',{exact:true}).waitFor();
    await page.locator('.topic-manager').screenshot({path:resolve('work','geo-question-topics.png')});
    await page.getByRole('button', { name: '监测任务' }).click();
    await page.getByRole('button', { name: '平台账号池' }).click();
    await page.locator('#accountForm input[name="label"]').fill('豆包门店二号');
    await page.getByRole('button', { name: '添加账号' }).click();
    await page.getByText('豆包门店二号', { exact: true }).waitFor();
    const defaultRow = page.locator('.accounts-table tbody tr').filter({ hasText: PLATFORMS.doubao.label }).filter({ hasText: '默认会话' });
    await defaultRow.getByRole('button', { name: '编辑账号' }).click();
    await page.locator('#editAccountForm input[name="label"]').fill('豆包主账号');
    await page.locator('#editAccountForm textarea[name="notes"]').fill('演示项目负责人');
    await page.getByRole('button', { name: '保存账号修改' }).click();
    await page.getByText('账号名称和备注已保存，登录状态与任务关联保持不变。').waitFor();
    await page.getByText('豆包主账号', { exact: true }).waitFor();
    await page.locator('#accountFilterForm input[name="search"]').fill('负责人');
    await page.getByRole('button', { name: '筛选账号' }).click();
    assert.equal(await page.locator('.accounts-table tbody tr').count(), 1);
    assert.match(await page.locator('.accounts-table').innerText(), /豆包主账号/);
    const accountRow = page.locator('.accounts-table tbody tr').filter({ hasText: '豆包主账号' });
    assert.match(await accountRow.innerText(), /尚未检查登录/);
    await accountRow.getByRole('button', { name: '检查登录状态' }).click();
    await accountRow.getByText('暂时无法确认', { exact: true }).waitFor();
    assert.match(await accountRow.innerText(), /检查时间/);
    assert.match(await accountRow.innerText(), /尚未采集/);
    await page.locator('#accountFilterForm select[name="platform"]').selectOption('deepseek');
    await page.getByRole('button', { name: '筛选账号' }).click();
    await page.getByText('没有匹配的账号，请调整筛选条件。').waitFor();
    await page.locator('#accountFilterForm select[name="platform"]').selectOption('');
    await page.locator('#accountFilterForm input[name="search"]').fill('');
    await page.getByRole('button', { name: '筛选账号' }).click();
    await page.locator('.accounts-table tbody tr').filter({ hasText: '豆包主账号' }).getByRole('button', { name: '编辑账号' }).click();
    await page.locator('#editAccountForm input[name="label"]').fill('豆包门店二号');
    await page.getByRole('button', { name: '保存账号修改' }).click();
    await page.getByText('该平台已有同名账号，请换一个名称', { exact: true }).waitFor();
    assert.equal(await page.locator('#editAccountForm input[name="label"]').inputValue(), '豆包门店二号');
    await page.getByRole('button', { name: '取消', exact: true }).click();
    await page.getByText('豆包主账号', { exact: true }).waitFor();
    await page.screenshot({ path: resolve('work', 'geo-accounts.png'), fullPage: true });
    await page.getByRole('button', { name: '监测任务' }).click();
    await page.locator('#taskForm input[name="name"]').fill('首轮监测');
    for(const box of await page.locator('#taskForm [name="topic"]').all())await box.check();
    await page.locator('#taskForm [data-action="applyTaskTopics"]').click();
    assert.equal(await page.locator('#taskForm [name="question"]:checked').count(),1,'两个专题同一问题只载入一次');
    await page.getByRole('button', { name: '创建任务' }).click();
    await page.getByText('首轮监测', { exact: true }).waitFor({ timeout: 5000 });
    assert.match(await page.locator('main').innerText(), /首轮监测/);
    assert.match(await page.locator('main').innerText(), /运行时选择/);
    await page.getByRole('button',{name:'问题池',exact:true}).click();
    const extraTopicQuestion=await page.locator('#topicMembershipForm [name="question"]').nth(1).getAttribute('value');
    await page.locator('#topicMembershipForm [name="question"]').nth(1).check();
    await page.locator('#topicMembershipForm [name="topicId"]').selectOption({label:'选择比较（1）'});
    await page.locator('#topicMembershipForm button').click();
    await page.getByText('选择比较 · 2 个问题',{exact:true}).waitFor();
    await page.getByRole('button',{name:'监测任务',exact:true}).click();
    await page.route('**/sync-topics',async route=>{const data=route.request().postDataJSON();await route.continue({postData:JSON.stringify({...data,expectedTopics:[]})});});
    page.once('dialog',dialog=>dialog.accept());
    await page.locator('[data-action="syncTaskTopics"]').first().click();
    await page.getByText('任务或专题已变化，请刷新后重新确认更新',{exact:true}).waitFor();
    await page.unroute('**/sync-topics');
    page.once('dialog',dialog=>dialog.accept());
    await page.locator('[data-action="syncTaskTopics"]').first().click();
    await page.getByText('任务已更新，历史问题清单保持不变。',{exact:true}).waitFor();
    await page.getByRole('button',{name:'问题池',exact:true}).click();
    await page.locator('#topicMembershipForm [name="question"][value="'+extraTopicQuestion+'"]').check();
    await page.locator('#topicMembershipForm [name="topicId"]').selectOption({label:'选择比较（2）'});
    await page.locator('#topicMembershipForm [name="operation"]').selectOption('remove');
    await page.locator('#topicMembershipForm button').click();
    await page.getByText('选择比较 · 1 个问题',{exact:true}).waitFor();
    await page.getByRole('button',{name:'监测任务',exact:true}).click();
    page.once('dialog',dialog=>dialog.accept());
    await page.locator('[data-action="syncTaskTopics"]').first().click();
    await page.getByText('任务已更新，历史问题清单保持不变。',{exact:true}).waitFor();

    await page.locator('button[data-action="runTask"]').first().click();
    await page.locator('#runTaskForm').waitFor();
    assert.equal(await page.locator('#runTaskForm input[name="account"]:checked').count(), 0);
    assert.equal(await page.locator('#runTaskForm input[name="question"]:checked').count(), 1);
    await page.getByRole('button', { name: '开始本次监测' }).click();
    await page.getByText('请为本次运行选择至少一个账号', { exact: true }).waitFor();
    await page.locator('#runTaskForm .account-option').filter({ hasText: '豆包门店二号' }).locator('input').check();
    await page.getByRole('button', { name: '取消', exact: true }).click();
    await page.getByRole('button', { name: '平台账号池' }).click();
    await page.locator('#accountForm select[name="platform"]').selectOption('deepseek');
    await page.locator('#accountForm input[name="label"]').fill('DeepSeek 新账号');
    await page.getByRole('button', { name: '添加账号' }).click();
    await page.getByRole('button', { name: '监测任务' }).click();
    await page.locator('button[data-action="editTask"]').first().click();
    await page.locator('#editTaskForm select[name="scheduleType"]').selectOption('daily');
    await page.locator('#editTaskForm .account-option').filter({ hasText: 'DeepSeek 新账号' }).locator('input').check();
    await page.getByRole('button', { name: '保存修改' }).click();
    await page.getByText('任务已更新，之后的新运行会使用新配置。').waitFor();
    assert.match(await page.locator('main').innerText(), /DeepSeek 新账号/);
    await page.screenshot({ path: resolve('work', 'geo-dashboard.png'), fullPage: true });
    const db = openDatabase(join(dir, 'test.db'));
    const task = db.prepare('SELECT * FROM tasks LIMIT 1').get();
    assert.deepEqual(JSON.parse(task.account_ids_json).map(accountId =>
      db.prepare('SELECT label FROM platform_accounts WHERE id=?').get(accountId).label), ['DeepSeek 新账号']);
    const question = db.prepare('SELECT * FROM questions WHERE brand_id=? LIMIT 1').get(task.brand_id);
    const runId = Number(db.prepare("INSERT INTO runs(task_id,status,total,done,started_at,finished_at) VALUES(?,'completed',1,1,?,?)")
      .run(task.id, new Date().toISOString(), new Date().toISOString()).lastInsertRowid);
    db.prepare("INSERT INTO results(run_id,question_id,platform,status,answer,citations_json,started_at,finished_at) VALUES(?,?,?,'succeeded',?,?,?,?)")
      .run(runId, question.id, 'doubao', '测试回答', JSON.stringify([
        { title: '参考资料一', url: 'https://example.org/a' },
        { title: '参考资料二', url: 'https://example.net/b' },
      ]), new Date().toISOString(), new Date().toISOString());
    db.prepare("INSERT INTO result_attempts(run_id,question_id,platform,status,error,error_code,started_at,finished_at,diagnostics_json) VALUES(?,?,?,'failed',?,?,?,?,?)")
      .run(runId, question.id, 'doubao', '系统异常', 'PROVIDER_ERROR', new Date().toISOString(), new Date().toISOString(),
        JSON.stringify({ stage: '提交问题', automaticRetry: true, editor: { inViewport: true, questionRetained: true } }));
    const accountId=JSON.parse(task.account_ids_json)[0];
    const brandSnapshot=JSON.stringify({...db.prepare('SELECT * FROM brands WHERE id=?').get(task.brand_id),website:'https://brand.example.com'});
    db.prepare('UPDATE runs SET brand_snapshot_json=?,task_snapshot_json=? WHERE id=?').run(brandSnapshot,JSON.stringify(task),runId);
    db.prepare('UPDATE results SET account_id=?,account_label=?,platform=? WHERE run_id=?').run(accountId,'演示账号','deepseek',runId);
    const secondRunId=Number(db.prepare("INSERT INTO runs(task_id,status,total,done,started_at,finished_at,brand_snapshot_json,task_snapshot_json) VALUES(?,'completed',1,1,?,?,?,?)").run(task.id,new Date().toISOString(),new Date().toISOString(),brandSnapshot,JSON.stringify(task)).lastInsertRowid);
    db.prepare("INSERT INTO results(run_id,question_id,account_id,account_label,platform,status,answer,citations_json,started_at,finished_at) VALUES(?,?,?,'演示账号','deepseek','succeeded',?,?,?,?)").run(secondRunId,question.id,accountId,'星河是候选工具',JSON.stringify([{title:'新来源',url:'https://example.org/new'}]),new Date().toISOString(),new Date().toISOString());
    db.close();
    await page.getByRole('button', { name: '采集结果', exact: true }).click();
    await page.getByRole('button', { name: '刷新' }).click();
    await page.getByRole('button', { name: '查看结果' }).last().click();
    await page.locator('main details > summary').filter({ hasText: question.text }).first().click();
    await page.getByText('测试回答', { exact: true }).waitFor({ timeout: 5000 });
    await page.getByText('按账号比较').waitFor();
    await page.getByText('正文引用（已采集 2 条）').click();
    assert.equal(await page.locator('a[href^="https://example."]').count(), 2);
    await page.getByText('执行记录（1 次，包含失败和重试）', { exact: true }).click();
    await page.locator('summary').filter({ hasText: '随后自动重试' }).click();
    await page.getByText('系统异常（PROVIDER_ERROR）', { exact: true }).waitFor();
    await page.getByText('输入框：在窗口可见范围内；原问题仍在输入框', { exact: true }).waitFor();
    await page.screenshot({ path: resolve('work', 'geo-results.png'), fullPage: true });
    await page.getByRole('button', { name: '分析报告', exact: true }).click();
    await page.getByRole('heading', { name: '问题 × 平台表现' }).waitFor();
    await page.getByRole('heading',{name:'品牌表现与数据差异',exact:true}).waitFor();
    await page.getByRole('heading',{name:'最近两次运行对比',exact:true}).waitFor();
    await page.getByRole('heading',{name:'逐问题历史轨迹',exact:true}).waitFor();
    await page.getByRole('heading',{name:'监测样本分布',exact:true}).waitFor();
    await page.locator('.report-sampling').screenshot({path:resolve('work','geo-sampling.png')});
    assert.equal(await page.getByText('数据质量说明',{exact:false}).count(),0);
    await page.locator('.report-sampling [data-action="reportEvidence"]').first().click();
    assert.match(await page.locator('#reportEvidence').innerText(),/统计对应的回答 · 2 条/);
    await page.getByRole('button',{name:'关闭证据'}).click();
    assert.equal(await page.locator('.change-stats').count(),1);
    assert.equal(await page.locator('.history-point').count(),2);
    await page.getByText('展开日期统计与引用变化',{exact:true}).click();
    await page.getByRole('heading',{name:'按日期的采样分母',exact:true}).waitFor();
    await page.locator('.report-history [data-id^="historyDay|"]').first().click();
    assert.match(await page.locator('#reportEvidence').innerText(),/统计对应的回答 · [12] 条/);
    await page.getByRole('button',{name:'关闭证据'}).click();
    await page.locator('.report-history [data-id^="historyChange|"]').first().click();
    assert.match(await page.locator('#reportEvidence').innerText(),/统计对应的回答 · 2 条/);
    await page.getByRole('button',{name:'关闭证据'}).click();
    await page.locator('.report-history [data-id^="historySource|"]').first().click();
    assert.match(await page.locator('#reportEvidence').innerText(),/统计对应的回答 · [12] 条/);
    await page.getByRole('button',{name:'关闭证据'}).click();
    await page.locator('.report-history').screenshot({path:resolve('work','geo-history.png')});
    await page.getByRole('button',{name:'可比回答对 1',exact:true}).click();
    assert.match(await page.locator('#reportEvidence').innerText(),/统计对应的回答 · 2 条/);
    await page.getByRole('button',{name:'关闭证据'}).click();
    await page.getByText('展开配对结果与已取得的引用变化',{exact:true}).click();
    await page.getByRole('button',{name:'对照配对回答',exact:true}).click();
    await page.getByRole('heading',{name:'最近两次成功回答对照'}).waitFor();
    assert.equal(await page.locator('.compare-columns > section').count(),2);
    await page.getByRole('button',{name:'关闭证据'}).click();
    await page.locator('.history-point').first().click();
    assert.match(await page.locator('#reportEvidence').innerText(),/统计对应的回答 · 1 条/);
    await page.getByRole('button',{name:'关闭证据'}).click();
    await page.screenshot({path:resolve('work','geo-run-changes.png'),fullPage:true});
    assert.equal(await page.getByRole('heading',{name:'优先查看的问题',exact:true}).count(),0);
    assert.equal(await page.getByRole('button',{name:'查看对应回答与优化步骤'}).count(),0);
    await page.getByRole('button',{name:'名称出现 1 条',exact:true}).click();
    assert.match(await page.locator('#reportEvidence').innerText(),/统计对应的回答 · 1 条/);
    await page.locator('#reportEvidence > details > summary').click();
    assert.ok(await page.locator('#reportEvidence .brand-evidence mark').count()>0);
    assert.match(await page.locator('#reportEvidence .brand-evidence').innerText(),/品牌全名：星河/);
    assert.match(await page.locator('#reportEvidence').innerText(),/星河/);
    await page.getByRole('button',{name:'关闭证据'}).click();
    await page.getByText('品牌名称出现在哪里 · 查看原文片段',{exact:true}).click();
    assert.ok(await page.locator('.question-name-evidence mark').count()>0);
    await page.locator('.question-name-evidence').screenshot({path:resolve('work','geo-brand-evidence.png')});
    await page.getByRole('button',{name:'名称未出现 1 条',exact:true}).click();
    assert.match(await page.locator('#reportEvidence').innerText(),/统计对应的回答 · 1 条/);
    await page.locator('#reportEvidence > details > summary').click();
    await page.locator('#reportEvidence').getByText('测试回答',{exact:true}).waitFor();
    await page.getByRole('button',{name:'关闭证据'}).click();
    await page.getByText('平台数据分布',{exact:true}).click();
    await page.getByText('名称出现与未出现的回答，分别引用了哪些页面 · 3 个',{exact:true}).click();
    assert.match(await page.locator('.report-facts > .question-fact').innerText(),/两组分母分别为 1 和 1/);
    await page.screenshot({path:resolve('work','geo-facts.png'),fullPage:true});
    await page.getByRole('button',{name:'查看对应回答',exact:true}).first().click();
    assert.match(await page.locator('#reportEvidence').innerText(),/统计对应的回答 · 1 条/);
    await page.getByRole('button',{name:'关闭证据'}).click();
    assert.equal(await page.locator('.report-metric').count(), 4);
    await page.locator('.report-metric').first().getByRole('button').click();
    await page.locator('#reportEvidence > details > summary').last().click();
    await page.locator('#reportEvidence').getByText('测试回答', { exact:true }).waitFor();
    assert.equal(await page.locator('#reportEvidence a[href^="https://example."]').count(), 3);
    await page.screenshot({ path:resolve('work','geo-analysis.png'), fullPage:true });
    await page.getByRole('button',{name:'关闭证据'}).click();
    assert.equal(await page.locator('#reportEvidence').count(),0);
    await page.getByRole('button',{name:'对照两次回答'}).click();
    await page.getByRole('heading',{name:'最近两次成功回答对照'}).waitFor();
    assert.equal(await page.locator('.compare-columns > section').count(),2);
    assert.match(await page.locator('.comparison').innerText(),/本次出现品牌/);
    await page.screenshot({path:resolve('work','geo-comparison.png'),fullPage:true});
    await page.keyboard.press('Escape');
    await page.getByText('具体引用页面 · 3 个',{exact:true}).click();
    await page.getByRole('button',{name:'查看引用它的回答'}).first().click();
    assert.match(await page.locator('#reportEvidence').innerText(),/统计对应的回答 · 1 条/);
    await page.getByRole('button',{name:'关闭证据'}).click();
    await page.locator('#reportFilterForm select[name="taskId"]').selectOption(String(task.id));
    await page.getByRole('button',{name:'应用筛选'}).click();
    const condition=await page.locator('#reportFilterForm select[name="cohort"] option').nth(1).getAttribute('value');
    await page.locator('#reportFilterForm select[name="cohort"]').selectOption(condition);
    await page.getByRole('button',{name:'应用筛选'}).click();
    assert.equal(await page.locator('#reportFilterForm select[name="cohort"]').inputValue(),condition);
    await page.locator('#reportFilterForm select[name="platform"]').selectOption('doubao');
    await page.getByRole('button',{name:'应用筛选'}).click();
    await page.getByText('当前筛选没有对应回答。',{exact:true}).waitFor();
    await page.getByRole('button',{name:'信源资产库',exact:true}).click();
    await page.getByRole('heading',{name:'信源资产库',exact:true}).waitFor();
    assert.equal(await page.locator('.source-site').count(),2);
    assert.equal(await page.locator('.table-scroll tbody tr').count(),3);
    await page.locator('#sourceFilterForm input[name="from"]').fill('2026-10-02');
    await page.locator('#sourceFilterForm input[name="to"]').fill('2026-10-01');
    await page.getByRole('button',{name:'应用筛选',exact:true}).click();
    await page.getByText('开始日期不能晚于结束日期',{exact:true}).waitFor();
    await page.locator('[data-action="sourceEdit"]').first().click();
    await page.locator('#sourceEditForm textarea').fill('暂存草稿');
    await page.route('**/api/source-library?**',route=>route.abort());
    await page.locator('.source-site').last().click();
    await page.locator('[data-notice].error').waitFor();
    await page.unroute('**/api/source-library?**');
    assert.equal(await page.locator('#sourceEditForm textarea').inputValue(),'暂存草稿');
    assert.equal(await page.locator('.table-scroll tbody tr').count(),3);
    await page.locator('[data-action="sourceEvidence"]').first().click();
    await page.getByRole('button',{name:'关闭来源证据',exact:true}).click();
    assert.equal(await page.locator('#sourceEditForm textarea').inputValue(),'暂存草稿');
    await page.getByRole('button',{name:'取消',exact:true}).click();
    assert.ok(!(await page.locator('.table-scroll').innerText()).includes('暂存草稿'));
    await page.locator('[data-action="sourceEdit"]').first().click();
    await page.locator('#sourceEditForm select[name="category"]').selectOption('owned');
    await page.locator('#sourceEditForm input[name="favorite"]').check();
    await page.locator('#sourceEditForm textarea').fill('已人工核对 <img src=x onerror=bad()>');
    await page.getByRole('button',{name:'保存资料',exact:true}).click();
    await page.getByText('来源分类、收藏和备注已保存。',{exact:true}).waitFor();
    assert.equal(await page.locator('.table-scroll img').count(),0);
    await page.screenshot({path:resolve('work','geo-source-library.png'),fullPage:true});
    await page.locator('#sourceFilterForm select[name="favorite"]').selectOption('1');
    await page.getByRole('button',{name:'应用筛选',exact:true}).click();
    await page.getByRole('heading',{name:'来源页面 · 1 个',exact:true}).waitFor();
    assert.equal(await page.locator('.table-scroll tbody tr').count(),1);
    await page.getByRole('button',{name:'查看回答',exact:true}).click();
    await page.locator('#sourceEvidence').waitFor();
    await page.locator('#sourceEvidence > details > summary').first().click();
    assert.match(await page.locator('#sourceEvidence').innerText(),/正文引用/);
    await page.getByRole('button',{name:'关闭来源证据',exact:true}).click();
    await page.getByRole('button',{name:'重置筛选',exact:true}).click();
    await page.getByRole('heading',{name:'来源页面 · 3 个',exact:true}).waitFor();
    assert.equal(await page.locator('.table-scroll tbody tr').count(),3);
    await page.locator('#sourceFilterForm select[name="taskId"]').selectOption(String(task.id));
    await page.getByRole('button',{name:'应用筛选',exact:true}).click();
    await page.locator('[data-action="sourceEdit"]').first().click();
    await page.locator('#sourceEditForm textarea').fill('不应跨品牌保留的草稿');
    await page.locator('[data-action="sourceEvidence"]').first().click();
    await page.getByRole('button',{name:'品牌资料',exact:true}).click();
    await page.getByRole('button',{name:'新建品牌',exact:true}).click();
    await page.locator('#brandForm input[name="name"]').fill('另一示例品牌');
    await page.locator('#brandForm input[name="category"]').fill('软件');
    await page.getByRole('button',{name:'保存品牌资料',exact:true}).click();
    await page.getByText('品牌资料已保存。',{exact:true}).waitFor();
    await page.getByRole('button',{name:'信源资产库',exact:true}).click();
    await page.getByRole('heading',{name:'来源页面 · 0 个',exact:true}).waitFor();
    assert.equal(await page.locator('#sourceFilterForm select[name="taskId"]').inputValue(),'');
    assert.equal(await page.locator('#sourceEditForm').count(),0);assert.equal(await page.locator('#sourceEvidence').count(),0);
    await page.getByRole('button',{name:'分析报告',exact:true}).click();
    await page.locator('#reportFilterForm').waitFor();
    assert.equal(await page.locator('#reportFilterForm select[name="taskId"]').inputValue(),'');
    assert.equal(await page.locator('#reportFilterForm select[name="platform"]').inputValue(),'');
    await page.locator('#reportFilterForm select[name="brandId"]').selectOption(String(task.brand_id));
    await page.getByRole('button',{name:'应用筛选',exact:true}).click();
    await page.getByRole('heading',{name:'问题 × 平台表现',exact:true}).waitFor();
    await page.getByRole('button',{name:'信源资产库',exact:true}).click();
    await page.getByRole('heading',{name:'来源页面 · 3 个',exact:true}).waitFor();
    assert.equal(await page.locator('#sourceEditForm').count(),0);
    assert.match(await page.locator('.table-scroll').innerText(),/已人工核对/);
    await page.locator('[data-action="sourceEvidence"]').first().click();
    await page.locator('#sourceEvidence').waitFor();
    await page.getByRole('button',{name:'采集结果',exact:true}).click();
    await page.getByRole('button',{name:'信源资产库',exact:true}).click();
    await page.getByRole('heading',{name:'来源页面 · 3 个',exact:true}).waitFor();
    assert.equal(await page.locator('#sourceEvidence').count(),0,'重新加载列表不能保留旧的缓存原文');
    await page.getByRole('button', { name: '采集结果', exact:true }).click();
    await page.getByRole('button',{name:'问题池',exact:true}).click();
    const oldBrand=await page.locator('#brandSelect').inputValue();
    const brandValues=await page.locator('#brandSelect option').evaluateAll(options=>options.map(o=>o.value));
    const switchBrand=brandValues.find(v=>v!==oldBrand);
    await page.route('**/api/brands/'+switchBrand+'/topics',route=>route.abort());
    await page.locator('#brandSelect').selectOption(switchBrand);
    await page.locator('.message.error').waitFor();
    assert.equal(await page.locator('#brandSelect').inputValue(),oldBrand,'专题请求失败不能提交品牌切换');
    await page.unroute('**/api/brands/'+switchBrand+'/topics');
    await page.getByRole('button',{name:'监测任务',exact:true}).click();
    assert.equal(await page.locator('#brandSelect').inputValue(),oldBrand,'切换页面后仍保持原品牌');
    await page.getByRole('button',{name:'问题池',exact:true}).click();
    await page.getByText('选择比较 · 1 个问题',{exact:true}).waitFor();
    await page.locator('#topicForm input[name="name"]').fill('空专题');
    await page.locator('#topicForm button').first().click();
    await page.getByText('空专题 · 0 个问题',{exact:true}).waitFor();
    await page.getByRole('button',{name:'信源资产库',exact:true}).click();
    await page.locator('#sourceFilterForm [name="topicId"]').selectOption({label:'空专题（0）'});
    await page.getByRole('button',{name:'应用筛选',exact:true}).click();
    await page.getByRole('heading',{name:'来源页面 · 0 个',exact:true}).waitFor();
    await page.getByRole('button',{name:'重置筛选',exact:true}).click();
    await page.getByRole('heading',{name:'来源页面 · 3 个',exact:true}).waitFor();
    await page.getByRole('button',{name:'采集结果',exact:true}).click();
    const paginationDb = openDatabase(join(dir, 'test.db'));
    const insertRun = paginationDb.prepare("INSERT INTO runs(task_id,status,total,done,started_at,finished_at) VALUES(?,'completed',0,0,?,?)");
    paginationDb.prepare('DELETE FROM runs WHERE id=?').run(secondRunId);
    for (let index = 0; index < 15; index++) insertRun.run(task.id, new Date().toISOString(), new Date().toISOString());
    paginationDb.close();
    await page.getByRole('button', { name: '刷新', exact: true }).click();
    await page.getByText('共 16 条 · 每页 10 条 · 第 1 / 2 页', { exact: true }).waitFor();
    const records = page.locator('.card').filter({ has: page.locator('.runs-pagination') });
    assert.equal(await records.locator('tbody tr').count(), 10);
    assert.equal(await page.getByRole('button', { name: '上一页', exact: true }).isDisabled(), true);
    await page.getByRole('button', { name: '下一页', exact: true }).click();
    assert.equal(await records.locator('tbody tr').count(), 6);
    assert.equal(await page.getByRole('button', { name: '下一页', exact: true }).isDisabled(), true);
    assert.match(await page.locator('main').innerText(), /运行 #1/);
    await page.getByRole('button', { name: '上一页', exact: true }).click();
    assert.equal(await records.locator('tbody tr').count(), 10);
    assert.equal(await page.getByRole('button', { name: '上一页', exact: true }).isDisabled(), true);
    const institutionUiDb=openDatabase(join(dir,'test.db'));
    institutionUiDb.prepare('UPDATE results SET answer=answer||? WHERE id=(SELECT MIN(id) FROM results)').run(' 推荐云海集团和云海公司。<img src=x onerror=window.institutionBad=true>');institutionUiDb.close();
    await page.getByRole('button',{name:'机构发现与对照',exact:true}).click();
    await page.getByRole('heading',{name:'回答中的机构',exact:true}).waitFor({timeout:3000}).catch(async error=>{throw Error(error.message+' UI '+await page.locator('main').innerText());});
    await page.getByRole('button',{name:'核对 云海集团',exact:true}).click();
    await page.locator('#institutionReviewForm [name="category"]').selectOption('peer');
    await page.locator('#institutionReviewForm [name="notes"]').fill('<img src=x onerror=window.institutionBad=true>人工核对');
    await page.getByRole('button',{name:'保存核对',exact:true}).click();
    await page.getByText('机构核对已保存；原回答未修改。',{exact:true}).waitFor();
    await page.locator('[data-action="institutionEvidence"][data-id="云海集团"][data-mode="body"]').click();
    await page.locator('#institutionProof').waitFor();
    assert.ok(await page.locator('#institutionProof mark').count()>0,'原文中有实际名称高亮');
    assert.equal(await page.locator('#institutionProof img').count(),0);assert.equal(await page.evaluate(()=>window.institutionBad),undefined);
    await page.getByRole('button',{name:'关闭证据',exact:true}).click();
    await page.getByRole('button',{name:'核对 云海公司',exact:true}).click();
    await page.locator('#institutionReviewForm [name="mergeInto"]').selectOption({label:'云海集团'});
    await page.getByRole('button',{name:'保存核对',exact:true}).click();
    await page.getByText('机构核对已保存；原回答未修改。',{exact:true}).waitFor();
    await page.getByRole('button',{name:'核对 云海公司',exact:true}).click();
    await page.locator('#institutionReviewForm [name="mergeInto"]').selectOption('');
    await page.locator('#institutionReviewForm [name="category"]').selectOption('ignore');
    await page.getByRole('button',{name:'保存核对',exact:true}).click();
    await page.getByText('机构核对已保存；原回答未修改。',{exact:true}).waitFor();
    await page.getByRole('button',{name:'补充漏识别名称',exact:true}).click();
    await page.locator('#institutionReviewForm [name="name"]').fill('云海');
    await page.locator('#institutionReviewForm [name="mergeInto"]').selectOption({label:'云海集团'});
    await page.getByRole('button',{name:'保存核对',exact:true}).click();
    await page.getByText('机构核对已保存；原回答未修改。',{exact:true}).waitFor();
    await page.getByRole('button',{name:'云海集团 · 详情',exact:true}).first().click();
    await page.locator('#institutionDetail').waitFor();assert.match(await page.locator('#institutionDetail').innerText(),/公共样本/);
    await page.waitForFunction(()=>!document.querySelector('#institutionFilterForm button').disabled);
    assert.equal(await page.locator('[data-action="institutionDetailPage"][data-section="questionPage"]').first().isDisabled(),true,'第一页上一页保持禁用');
    assert.equal(await page.locator('[data-action="institutionDetailPage"][data-section="sourcePage"]').last().isDisabled(),true,'末页下一页保持禁用');

    assert.ok(await page.getByRole('heading',{name:'平台分布',exact:true}).count());assert.ok(await page.getByRole('heading',{name:/相关来源/}).count());
    await page.locator('#institutionDetail [data-action="institutionEvidence"][data-mode="body"]').click();await page.locator('#institutionProof').waitFor();
    assert.ok(await page.locator('#institutionProof mark').count()>0);assert.equal(await page.locator('#institutionProof img').count(),0);
    await page.locator('[data-action="institutionEvidence"][data-mode="withoutOwn"][data-context*="questionId"]').click();assert.equal(await page.locator('#institutionProof article').count(),1);
    await page.locator('[data-action="institutionEvidence"][data-context*="sourceRelation"][data-mode="body"]').first().click();assert.equal(await page.locator('#institutionProof article').count(),1,'来源证据只返回使用该链接且正文提及的回答');
    await page.locator('[data-action="institutionEvidence"][data-context*="sourceRelation"][data-mode="citation"]').first().click();await page.getByRole('heading',{name:'名称证据 · 0 条',exact:true}).waitFor();assert.equal(await page.locator('#institutionProof article').count(),0,'通用来源标题不冒充机构名称匹配');
    await page.route('**/api/institutions/detail?*',route=>route.abort());
    await page.locator('[data-action="institutionDetailPage"][data-section="sourcePage"]').last().evaluate(el=>{el.disabled=false;el.click();});
    await page.waitForTimeout(150);assert.equal(await page.locator('#institutionDetail').count(),1,'详情翻页请求失败保留旧范围');
    await page.unroute('**/api/institutions/detail?*');
    await page.locator('#institutionDetail [data-action="institutionEvidence"][data-mode="body"]').click();await page.getByRole('heading',{name:'名称证据 · 1 条',exact:true}).waitFor();
    await page.screenshot({path:resolve('work','geo-institution-detail.png'),fullPage:true});
    assert.equal(await page.locator('[data-action="institutionEvidencePage"]').first().isDisabled(),true);assert.equal(await page.locator('[data-action="institutionEvidencePage"]').last().isDisabled(),true,'证据末页保持禁用');
    await page.getByRole('button',{name:'返回机构列表',exact:true}).click();assert.equal(await page.locator('#institutionDetail').count(),0);assert.equal(await page.locator('#institutionProof').count(),0);
    await page.screenshot({path:resolve('work','geo-institutions.png'),fullPage:true});
    await page.locator('#institutionFilterForm [name="topicId"]').selectOption({label:'空专题（0）'});
    await page.locator('#institutionFilterForm button').click();
    await page.getByText('当前有效回答 0 条 · 公共比较样本 0 条 · 点名或其他类型 0 条',{exact:true}).waitFor();
    await page.getByRole('button',{name:'问题池',exact:true}).click();
    const emptyTopicRow=page.locator('.topic-list .row').filter({hasText:'空专题'});
    page.once('dialog',dialog=>dialog.accept());await emptyTopicRow.getByRole('button',{name:'删除专题',exact:true}).click();
    await page.getByRole('button',{name:'机构发现与对照',exact:true}).click();
    await page.getByText('此前筛选的专题已删除，已恢复全部专题，请重新筛选。',{exact:true}).waitFor();
    assert.equal(await page.locator('#institutionFilterForm [name="topicId"]').inputValue(),'');
    await page.locator('#institutionFilterForm [name="brandId"]').selectOption(switchBrand);
    await page.locator('#institutionFilterForm button').click();
    await page.getByText('当前有效回答 0 条 · 公共比较样本 0 条 · 点名或其他类型 0 条',{exact:true}).waitFor();
    assert.equal(await page.locator('#institutionReviewForm').count(),0);assert.equal(await page.locator('#institutionProof').count(),0);assert.equal(await page.getByRole('button',{name:'核对 云海集团',exact:true}).count(),0,'机构核对不跨品牌');

  } finally {
    await browser?.close();
    child.kill();
    await new Promise(done => child.exitCode !== null ? done() : child.once('exit', done));
  }
});
